# ã‚µã‚¤ãƒ‰ãƒãƒ¼

- label: ã¯ã˜ã‚ã«
  items:
    - label: 'ã‚ˆã†ã“ã'
      link: '/'
    - label: 'å…¥ã‚Šæ–¹'
      link: '/join'
    - label: 'ãƒ«ãƒ¼ãƒ«'
      link: '/terms'
- label: ã‚‚ã£ã¨è©³ã—ã
  items:
    - label: 'é‹å–¶ä¸€è¦§'
      link: '/staff'
    - label: 'ã‚ˆãã‚ã‚‹è³ªå•'
      link: '/faq'
    - label: 'å†…éƒ¨ã‚¢ãƒ‰ãƒ¬ã‚¹'
      link: '/address'

# å¤–éƒ¨ãƒªãƒ³ã‚¯

- label: å¤–éƒ¨ãƒªãƒ³ã‚¯
  items:
    - label: 'ğŸ”— Linktree'
      link: https://linktr.ee/azisaba
    - label: 'ğŸ’¸ å¯„ä»˜'
      link: https://store.azisaba.net
    - label: 'âœ… ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹'
      link: https://status.azisaba.net
    - label: 'ğŸ“¥ ãƒªã‚½ãƒ¼ã‚¹ãƒ‘ãƒƒã‚¯'
      link: https://packs.azisaba.net
- label: å”åŠ›ã¨ææº
  items:
    - label: 'DDPS æ§˜'
      link: https://ddps.jp
    - label: 'ã¡ã‚ƒã¶ã ã„ã•ï½ã°ï½ æ§˜'
      link: https://chabudai.xyz
    - label: 'Strife æ§˜'
      link: https://twitter.com/STRIFE_mcserver
    - label: 'Coretol æ§˜'
      link: https://matchatb.wixsite.com/coretol
